spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/netzgrafikeditor
  jooq:
    sql-dialect: Postgres
  flyway:
    enabled: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

endpoints:
  web:
    cors:
      path-mappings: /**
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"

logging:
  level:
    org.springframework: INFO

auth:
  audience:
    service-name: ${AUTH_SERVICE_NAME}

# only active in 'local' profile
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
