blank_issues_enabled: false
contact_links:
  - name: Netzgrafik-Editor Community Forum
    url: https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/discussions
    about: Please discuss you ideas or issue there as well.
