on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: maven

  release:
    needs: release-please
    if: needs.release-please.outputs.releases_created
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.release-please.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          # TODO: Is this the right distribution for this project?
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Create container image
        run: |
          mvn spring-boot:build-image \
            -Dmaven.test.skip=true \
            -Dgithub.image.release=true \
            -Dimage.version=$VERSION
